name: adar1-scrna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - scanpy=1.11.5
  - anndata=0.11.4
  - pandas=2.3.3
  - numpy=2.3.5
  - scipy=1.16.3
  - matplotlib=3.10.8
  - lifelines=0.30.3
  - openpyxl=3.1.5
  - python-igraph=1.0.0
  - leidenalg=0.11.0
  - umap-learn=0.5.9.post2